apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.tracerip.io
spec:
  scope: Namespaced
  group: tracerip.io
  names:
    kind: Network
    plural: networks
    singular: network
    shortNames:
      - ntw
      - ntws
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ips.tracerip.io
spec:
  scope: Namespaced
  group: tracerip.io
  names:
    kind: IP
    plural: ips
    singular: ip
    shortNames:
      - ip
      - ips
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true