apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  externalIPs:
    - 116.203.228.23
  selector:
    app: mongodb